### PR TITLE
Support to show ICS invite as attachments

### PR DESCRIPTION
**Pull request by nirmit**
ICS invites are currently not displayed correctly in Nylas.  This PR adds support to extract calendar files and store them as attachments.  The attachment is called  `Event.ics`.  

First implementation for #132

### CODE REVIEW

**Comment by seesemichaelj** [comment]
and this works? seems too good to be true, but I have no way to really know haha

**Comment by nirmit** [comment]
well, let's try this then!  Can I send you a test invite?

**Comment by nirmit** [comment]
Just sent you one.  Can you try and see if you got the invite as an attachment?  The email body must be blank!

**Comment by seesemichaelj** [comment]
can you send it to 'nylascommunity@gmail.com'? takes awhile for my main email to sync on dev database

**Comment by nirmit** [comment]
Done!  You should have it now.

**Comment by nirmit** [comment]
The idea behind the solution is to instruct Nylas to extract ICS as attachments.  To do this, I add the correct content type for ICS invites so that Nylas knows it has to decode the content and store it as an attachment.  It was really that simple.

**Comment by seesemichaelj** [comment]
I did receive an attachment and it looks like a valid file with relevant info. However it doesn't seem to import into a calendar application (Google Calendar and elemantary OS calendar). It doesn't error, but no event shows up. The date looks valid to be today from 12:30PM EST to 1:00PM EST when looking at the contents of the ICS file

**Comment by nirmit** [comment]
The date/time is correct.  The ICS content is what exchange sent and its simply storing it as .ics.  I don't have elementaryOS but I use Mac and I was able to import it in the Calendar app. 

This is strange.

**Comment by seesemichaelj** [comment]
Have you tried downloading the file that is in your sent box in Nylas and importing that? I'm just hoping it didn't corrupt any of the content (or not download all of it)

**Comment by nirmit** [comment]
Yes.  I was able to download and import it correctly.

**Comment by seesemichaelj** [comment]
@nirmit when you add commits to a branch it adds them to the pull request. this is why we use separate branches than master for individual features. I don't necessarily want to accept https://github.com/nylas-mail-lives/nylas-mail/pull/133/commits/fe416295240d97df28a1af1b3aa00fc198d67a34 as part of this PR

**Comment by nirmit** [comment]
Got it.  I am still trying to get a hang of it.  Will separate branches.

**Comment by dweremeichik** [comment]
This looks good to merge now. 👍

**Pull request merged**
