### PR TITLE
Change Contributing.md

### PR DESCRIPTION
**Pull request by step21**
Should be deleted as the procedure outlined does not apply to the fork.

### CODE REVIEW

**Comment by seesemichaelj** [comment]
This definitely should not be deleted. If anything it should be updated with the correct material.

**Comment by step21** [comment]
Sure. Did you guys talk about what you require, which process you want to have for contributions?

**Comment by seesemichaelj** [comment]
I guess we did not really discuss this, but ideally we would like something in place. Any thoughts @dweremeichik? Any suggestions @step21? I would just like to have this file still be there even if it had a "We're working on it" versus removing it

**Comment by dweremeichik** [comment]
Let's have this discussion here if possible. @tsikerdekis @danielmelogpi @mayurdw @GrayW 
Feel free to at someone to have them way in.

**Comment by tsikerdekis** [comment]
I think the file should be revised but not deleted. There are some parts in regards to how one should contribute that are relevant. As for the CLA or nylas' link that is something that it will have to be revised so that it will say that this is a fork from the original.

**Comment by dweremeichik** [comment]
Here are my thoughts:

1. The link in the readme is a hard link to the nylas repo. That will need to be resolved.
1. I don't think that the contributing guide should be under the "plugin" heading in the readme.
1. We should get rid of the first paragraph of "Filing an issue".
1. Get rid of the CLA info in the "Pull Requests" section.

Any ideas for additions/removal of content on this are certainly welcome, we should at least strive for some manner of organized chaos within the repo. I believe a well structured contributing guide can go a long way towards that goal.

**Comment by seesemichaelj** [comment]
I agree with the suggestions by @dweremeichik. I don't really have many suggestions right now in our infancy. There will likely be more changes down the road after a few rodeos.

**Comment by mayurdw** [comment]
Sorry I have been absent. I just finished a hackathon this weekend and now I am slowly getting back. 

In addition to the changes suggested, add our slack link (even if Readme already has it). Considering the past PRs have been small ones we can technically remove the paras about squashing commits but we need to keep the one about Git Message (nitpicking really).

We can link our current issues which are "contributor wanted" tagged. This way they know where to contribute towards (@dweremeichik has mentioned that so many times in the slack channel)
Nothing else for now

**Comment by seesemichaelj** [comment]
We should not put links too active issues. That would require constantly updating to this document. We could put a link which opens the issues page filleting by that label though.

**Comment by seesemichaelj** [comment]
I'm going to call this PR obsolete now. someone will need to open a new PR with the appropriate changes (perhaps with some further discussion on an issue)

**Pull request closed without merging**
