### PR TITLE
Updated linux menubar

### PR DESCRIPTION
**Pull request by LiHRaM**
# Linux menubar separator caused uneccesary whitespace.

----
Here's a screenshot of what it looked like before the change:

image

---
And here's what it looked like after.
image

### CODE REVIEW

**Comment by dweremeichik** [comment]
I think it is still used. https://github.com/nylas-mail-lives/nylas-mail/blob/18545f3add6cefe2af36ae80f5dd427bb1752ad2/packages/client-app/internal_packages/message-list/lib/message-list.cjsx#L101

Would be nice to figure out a way to only add it when needed however.

**Comment by LiHRaM** [comment]
@dweremeichik Yeah, the thread menu changes when you open a message, but removing the separator makes no difference in the way that looks.

Before:

image

After:

image

**Comment by LiHRaM** [comment]
Included some work to solve #112

**Comment by seesemichaelj** [comment]
Whoa! Why are you disabling the Alt menu? There's no reason to disable that functionality unless it's completely redundant (which I don't think it is).

**Comment by LiHRaM** [comment]
@seesemichaelj - I'd like to argue for disabling the alt menu, since the hamburger menu effectively replaces its every function. Unless you think it's more aesthetically pleasing. 

Either way, we can just make it an option to tick/untick in preferences and leave it at that. What do you think?

**Comment by seesemichaelj** [comment]
I think until we replicate all of the options in the hamburger menu, we can't get rid of it. I see no reason for us to add a check box when the Alt key works just as good. @dweremeichik thoughts?

**Comment by LiHRaM** [comment]
@seesemichaelj  - I feel like we're working with some misconceptions here. Are there any options in the Alt menu that aren't in the hamburger menu? I haven't noticed anything, but feel free to correct me if I'm wrong.

Neither do I think the checkbox would replace the alt key. It would just enable the ability to view the menu with the alt key. I've noticed, for example, that when I alt-tab to Nylas it turns on the menu. Since I already have the hamburger menu, that's a minor irritant. I'd like to just be able to disable that behaviour.

**Comment by lamixer** [comment]
My 2 cents: as I have used Nylas Mail on Fedora 26 (Gnome 3), the 'hidden' menu is unattractive when it is shown, and it's a pretty unusual UI (in my experience) to have to press some hot button (Alt) to reveal a menu bar. Some users might have even more annoying side affects with their use of the Alt button than LiRaM does.

If the hamburger menu can reveal all menus then that should be the only way to access menus.

**Comment by seesemichaelj** [comment]
I'm fine if everything in the menu bar is in the Alt menu. Im fairly certain there are missing actions. If you can verify the options and make the necessary changes, I will be okay with disabling the Alt menu

**Comment by lamixer** [comment]
This is kind of an important UI decision, and compatibility with behaviour on other DEs and OSes should be considered.

One thing the Alt menu offers is to show what the key bindings are for the various menu options - does the hamburger menu do that?

My main problem with the Alt menu is it was difficult as a new user to know it was even there, and how to activate it. Second problem is that it's just kind of 'old fashioned' looking, and one of the pleasing things about Nylas Mail is the fresh look of it.

**Comment by seesemichaelj** [comment]
Totally understand @lamixer! I'm going to look at this more today and then we'll get back to everybody

**Comment by seesemichaelj** [comment]
The good news is that I'm fairly sure now that they're programmed to be identical. This means we can go ahead and disable the Alt menu :+1: 

The bad news is that the menu for Windows is different for Linux, and I like the one for windows better haha:

**Comment by seesemichaelj** [comment]
Can we change the linux menu to have that layout instead?

**Comment by LiHRaM** [comment]
@seesemichaelj I'll have a look mate.

**Comment by LiHRaM** [comment]
Okay. The windows menu could be copied over to the linux one without any problems.
Here is the result:
image

**Pull request merged**
