### PR TITLE
Remove some n1 cloud api calls

### PR DESCRIPTION
**Pull request by simonft**
This removes an API call triggered on signing in to a IMAP account and some delta connections code that wasn't being used anywhere. Both are no longer useful after Nylas's removal of most of the cloud-based sync functionality. Further details on each can be found in the respective commit messages.

### CODE REVIEW

**Comment by seesemichaelj** [comment]
kudos for picking the correct branch!

**Comment by dweremeichik** [comment]
Looks decently reasonable. Would you mind explaining more in the description what bits were removed, and why for historical reasons.

**Comment by simonft** [comment]
I've updated the description of the MR and adding details to both of the commit messages.

**Comment by dweremeichik** [comment]
Reopening.

**Pull request merged**
