### PR TITLE
[PPA] Fixes issue where some Ubuntu derivatives would not add the appropriate PPA.

### PR DESCRIPTION
**Pull request by dweremeichik**
Some Ubuntu derivatives were not adding the appropriate PPA under the old "name based" system (elementary os, I'm looking at you...). The new system proposed here looks upstream to determine if it is okay to add. Note, we don't currently use this functionality, but perhaps some day someone will.

### CODE REVIEW

**Comment by dweremeichik** [comment]
Unfortunately it is more difficult to patch into Mailspring, as Ben modified that file a bunch...

**Comment by seesemichaelj** [comment]
well i don't think this will serve much purpose in a couple of days :P shall i close this PR then?

**Comment by seesemichaelj** [comment]
you're not referring to 2.2.0, right? 2.2.0 isn't a mailspring merge, its a nylas merge

**Comment by dweremeichik** [comment]
No, we should still pull this in for anyone who would like to use it in the future. I am making a separate PR for Mailspring.

**Comment by alexanderadam** [comment]
Just to be sure if I got this correctly: this PR just fixes the process of adding the legacy-PPA as there is no PPA for the `nylas-mail-lives` fork — right?

**Comment by dweremeichik** [comment]
That would be correct. It's a fix for if it ever gets a PPA in the future.

**Comment by alexanderadam** [comment]
Thank you for your fast response!
Okay, so I guess it would be okay then to open an issue for creating an PPA? :wink:

**Comment by dweremeichik** [comment]
I don't see why not. 👍

**Comment by seesemichaelj** [comment]
This PR is no longer applicable due to the conflicts of the new merge. Please rebase to the new `master` branch and bring over your fixes. You can cherry-pick the commits. Please see the `v2.1.0` branch to see the old master branch. Thanks!

**Pull request closed without merging**
