### PR TITLE
Displaying conversation in a descending chronological order

### PR DESCRIPTION
**Pull request by tsikerdekis**
In reference to #20

### CODE REVIEW

**Comment by dweremeichik** [comment]
@tsikerdekis I'm curious, have you taken a look at any of the specs/tests yet? I have not, but I am wondering if there is anything that might apply to this.

**Comment by dweremeichik** [comment]
Ah, think I found where the tests for that module are: nylas-mail/packages/client-app/internal_packages/message-list/spec/message-list-spec.cjsx. Perhaps we should consider adding a test to make sure the list will order correctly based on the setting property. I am looking into getting (at least) the linux travis ci working again so we will know when we break things.

**Comment by dweremeichik** [comment]
@tsikerdekis I am good with merging this if we create a new issue to remind us to create a test for this once we figure out more about how the testing process works.

**Comment by tsikerdekis** [comment]
I created #27 for this.
Quick question: merge or squash and merge? I think squash is better since there are 4 commits.

**Comment by dweremeichik** [comment]
We should make use of GitHub's nice squash and merge feature 😎

**Pull request merged**
