### PR TITLE
Fix missing shortcuts in the application menu.

### PR DESCRIPTION
**Pull request by CvX**
Fixes https://github.com/nylas/nylas-mail/issues/2305

### CODE REVIEW

**Comment by seesemichaelj** [comment]
Next time, we would have appreciated you to open an issue on this repository referencing that issue so we could open it up for discussion if need be. I know it's redundant, but it helps us help you :)

**Comment by seesemichaelj** [comment]
Do we know if this problem arises anywhere else in the code? I see several comments mentioning `cmd` but I believe they all use `command` in the code

**Comment by CvX** [comment]
Sorry for the drive-by PR! 😅

I'm no longer using nylas mail, just recovering an old PR that might be still useful for current users of the forks (as pointed out by @dweremeichik here: https://github.com/nylas/nylas-mail/pull/3572#issuecomment-334910260)!

This change fixes all the keyboard shortcut issues I've stumbled on. I believe all other occurrences of "cmd" are only in comments and in displayed text, not in keybinding code. 🍻

**Comment by dweremeichik** [comment]
Thanks @CvX Happy Hacktoberfest!

**Pull request merged**
