### PR TITLE
Replaced this subdirectory Readme with an updated one

### PR DESCRIPTION
**Pull request by step21**
Replaced this subdirectory Readme with an updated one, as the old one was still mentioning much of Nylas and saying 'We're hiring' stuff like that

### CODE REVIEW

**Comment by dweremeichik** [comment]
@seesemichaelj Thoughts on this? I don't see the need to repeat content from the main README.

**Comment by step21** [comment]
Sure, I guess it could also be deleted. But the old one was also partially repeating info and generally just wrong. (such as many references to the original Nylas/N1)

**Comment by dweremeichik** [comment]
@step21 I don't think we should delete the whole thing. There is definitely some relevant info that we should have there.

**Comment by step21** [comment]
Like what? Based on checking again just now, all info is in the main readme. The old readme in the subdirectory even still mentions N1 at one or two places.

**Comment by dweremeichik** [comment]
I may have been thinking about a readme in another package. I think the best option may be to kill this one for now, as it is purely redundant. If you would kindly edit this PR to delete the readme in the client-app folder, I'll merge it in.

**Comment by step21** [comment]
Done

**Comment by dweremeichik** [comment]
Thanks @step21 happy hacktoberfest!

**Comment by step21** [comment]
Thanks! If I may ask, where did you see that I was participating?
Tbh for NML issues, my js/react/electron knowledge is really not enough I think. Or the codebase is just too big ^^

**Comment by seesemichaelj** [comment]
we've just been saying happy hacktoberfest for the fun of it to all of the PRs haha

**Comment by step21** [comment]
Nice, lol. Though in this case it wasn't tagged so not true ^^

**Comment by seesemichaelj** [comment]
Doesn't need to be tagged actually. 4 PRs on a public repo is all it takes; regardless if its tagged

**Comment by dweremeichik** [comment]
I didn't specifically see that you were participating. Just spreading the joy!
It is a particularly large codebase for sure. It's all about breaking the issue down into small bits.

**Comment by seesemichaelj** [comment]
https://hacktoberfest.digitalocean.com/stats/step21 your nylas one shows up!

**Comment by dweremeichik** [comment]
You beat me to it... Lol

**Comment by step21** [comment]
Ah lol, good to know.
Sure, breaking down helps but f.e. I was trying to see if I could do sth about the 80 char option ... so somhow have to find the editor or whatever it is called, then add an option somewhere... and I'm lost.

**Pull request merged**
