### PR TITLE
Linux menu button

### PR DESCRIPTION
**Pull request by LiHRaM**
- Added three dots icon as a possible replacement for the hamburger design.
- Removed the button-y look of the menu button. More consistent with Windows client. (Besides the whole three dots thing.)

---

button-preview-4

### CODE REVIEW

**Comment by seesemichaelj** [comment]
@dweremeichik are we fine with the large circle? it could be smaller, I guess i don't really care. just food for thought

**Comment by seesemichaelj** [comment]
also @LiHRaM do we need to add attribution for wherever you pulled the icon from?

**Comment by dweremeichik** [comment]
I mean, perhaps we could trim the circle down if you'd like. It doesn't currently get clipped does it?

**Comment by LiHRaM** [comment]
@seesemichaelj It's from material.io. They don't require attribution, no.

**Pull request merged**
