### PR TITLE
Display the event header

### LINKED ISSUE #132: Calendar Invites don't show up in the body
The body shows as blank.  It seems to be an issue with the "events" attribute in the message object.  This is specific to ICS invite based emails.

This issue can be split up into the below desired functionality:
- [x] (@nirmit completed) Show ICS as attachment
- [ ] (pending review) Show invite content (date, time, timezone if specified, name, location, description, etc) with no action buttons
- [ ] (Unassigned) Implement RSVP action buttons

### PR DESCRIPTION
**Pull request by nirmit**
This PR adds the event header for all calendar invites.

1. Parse the event information and store it in the `events` column.
2. Display the event information as a header (Uses the existing `events` module).
2. Add a calendar icon in the thread list view for emails that contain invitations.

Improvements/Tests requested:
1.  Suggest a better UI Icon to display a calendar invite in the list view.
2.  Test the migration on other OSes.  If it doesn't work, can someone look into it?

Fixes #132 (Point no. 2)

### CODE REVIEW

**Comment by dweremeichik** [comment]
@nirmit any chance we could get some screenshots of what this looks like please?

**Comment by nirmit** [comment]
Sure.

The Email Header for Invites
header-view

The Thread List View (notice the icon for calendar invites)
screen shot 2017-11-17 at 3 56 06 pm

**Comment by seesemichaelj** [comment]
What's wrong with the icon in the list view? That looks nice to me

**Comment by dweremeichik** [comment]
We can merge this in and let people play around with it in Master.

**Pull request merged**
