### PR TITLE
fix extracting multipart/alternative parts

### LINKED ISSUE #72: Can not display mail from Amazon (HTML-mail?)
##### Are there any related issues?

...
https://github.com/nylas/nylas-mail/issues/3434
##### What operating system are you using?
...
Windows 10 Pro 1703 x64
##### What version of Nylas Mail are you using?
...
2.1.0
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
It does not appear to be related to a specific mail provider.
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
All text from Amazon will not be displayed.
capture
--

### PR DESCRIPTION
**Pull request by MattSkala**
When extracting `multipart/alternative` part, it is currently assumed that the mail contains at least one `text/html` part. While that's the case most of the time, it doesn't have to be always true. There are cases when multipart message contains just a single single `text/plain` part. (Fixes #72).

The proposed fix conforms to RFC 2046:
_"The use of the "multipart" media type with only a single body part may be useful in certain contexts, and is explicitly permitted."_
_"In general, the best choice is the LAST part of a type supported by the recipient system's local environment."_

I would be willing to write some tests, but was unable to run them for client-sync package. Is there currently a way to execute them?

### CODE REVIEW

**Comment by seesemichaelj** [comment]
@MattSkala are you participating in Hacktoberfest (https://hacktoberfest.digitalocean.com/)? If so, we could close this PR and open it again tomorrow to have it count?

**Comment by seesemichaelj** [comment]
I've been looking at this, and it may be related to #82; can you confirm @simonft?

**Comment by dweremeichik** [comment]
@seesemichaelj this appears to be for RX. What @simonft is working on is for TX.

**Comment by MattSkala** [comment]
@seesemichaelj That's OK, you can keep it open.

**Comment by dweremeichik** [comment]
I do wonder what we see our supported parts as being. I would assume text & or HTML. The rfc allows for other format as well, does blindly choosing the last one make sense? Or do we explicitly check for HTML and then fall back to text? I'm not sure what the other possible formats may be. Also by always choosing the last part, we are trusting all clients out there to do the right thing.

Just thinking out loud, let me know what you think.

**Comment by seesemichaelj** [comment]
I'll look at this tomorrow

**Comment by seesemichaelj** [comment]
I'm also afraid of ignoring the warning of complexness that Nylas put in the comments and just going for it. I'm wondering if there are email clients that screw stuff up we're not aware of currently

**Comment by dweremeichik** [comment]
After more thought on it, and looking over the RFC a bit more, the strategy in my head is: 

1. Prefer text/HTML

1. Fall back to text/enriched

1. Fall back to text/plain

1. Settle for whatever type may be available (not the last version, but the first, as we don't recognize the types, but the first should be the "plain" format)

My reasoning: there are a ton of mime types, and we can't display the majority of them in the fashion intended, so we try to do the right thing, and then fall back to whatever is left. Perhaps some day we could pretty print things like text/yaml etc.

**Comment by MattSkala** [comment]
If I understand the code correctly, until now, we supported only text/html type in multipart/alternative messages. That resulted in a blank content displayed when that type was not present.

This commit supports both text/plain and text/html, preferring the type whichever is positioned later in the message.

Please note that to get alternative parts, we are calling _getDesiredMIMEParts recursively. This function filters out unsupported parts and returns only parts with types present in desiredTypes set, currently text/plain and text/html. Therefore, it shouldn't happen that we select a part with an unsupported type. (https://github.com/MattSkala/nylas-mail/blob/47b6c95c162423f2868b026691a7b7ab3726d3e3/packages/client-sync/src/local-sync-worker/sync-tasks/fetch-messages-in-folder.imap.es6#L188)

Are you suggesting to support also text/enriched and fallback to any type available?

**Comment by dweremeichik** [comment]
So, it appears that I missed that bit when I reviewed this before. In that case, we can safely ignore my request, and choose the last supported part. I will go ahead and merge this in. Thanks for the great work!

**Pull request merged**
